[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/service"
  to = "/expertise"
  status = 301
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/about"
  to = "/hetverhaal"
  status = 301
  force = true
  headers = {X-From = "Netlify"}