[build]
publish = "public"
command = "hugo --enableGitInfo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --enableGitInfo --gc --minify"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --enableGitInfo --gc --minify"

#[context.branch-deploy.environment]
#HUGO_VERSION = "0.36"


[[redirects]]
  from = "/service"
  to = "/expertise"
  status = 301
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/about"
  to = "/hetverhaal"
  status = 301
  force = true
  headers = {X-From = "Netlify"}