[build]
publish = "public"
command = "hugo --enableGitInfo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --enableGitInfo --gc --minify  && echo -e 'User-agent: *\nDisallow: /' > public/robots.txt"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --enableGitInfo --gc --minify  && echo -e 'User-agent: *\nDisallow: /' > public/robots.txt"

[context.dev]
command = "hugo --buildDrafts -b https://dev--trusting-kirch-c95cf8.netlify.app --enableGitInfo --gc --minify && echo -e 'User-agent: *\nDisallow: /' > public/robots.txt"

[context.daniel]
command = "hugo -b https://daniel.kroescontrol.nl --enableGitInfo --gc --minify  && echo -e 'User-agent: *\nDisallow: /' > public/robots.txt"

[context.branch-deploy.environment]
HUGO_ENV = "nonprod"

[[redirects]]
  from = "/service"
  to = "/expertise"
  status = 301
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/about"
  to = "/hetverhaal"
  status = 301
  force = true
  headers = {X-From = "Netlify"}
